import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import Header from "@/components/custom/Header";
import { ThemeProvider } from "@/components/providers/ThemeProvider";
import { Footer } from "@/components/custom/Footer";
import ReduxStoreProvider from "@/components/providers/ReduxStoreProvider";
import CartSidebar from "@/components/custom/cart/CartSidebar";
import SyncCartOnLogin from "@/components/custom/SyncCartOnLogin";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en" suppressHydrationWarning>
        <body className={inter.className}>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            {/* <Navbar /> */}
            <ReduxStoreProvider>
              <SyncCartOnLogin />
              <div className="min-h-screen bg-background text-foreground flex flex-col">
                <Header />
                <main>{children}</main>
                <div className=" bg-secondary text-secondary-foreground">
                  <div className="container mx-auto">
                    <Footer />
                  </div>
                </div>
              </div>
              <CartSidebar />
            </ReduxStoreProvider>
          </ThemeProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
